using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace LostAndFound.EditorTools
{
    /// <summary>Writes docs/nudges.md: every nudge Agnes can give on the best path through the week, in the order a
    /// stuck player would see them, so the wording can be read through in one place.</summary>
    public static class NudgeDump
    {
        [MenuItem("Lost & Found/Write docs/nudges.md")]
        public static void Write()
        {
            var parts = new List<ContentRoot>();
            foreach (var guid in AssetDatabase.FindAssets("t:TextAsset", new[] { "Assets/Game/Resources/Content" }))
                parts.Add(JsonUtility.FromJson<ContentRoot>(AssetDatabase.LoadAssetAtPath<TextAsset>(AssetDatabase.GUIDToAssetPath(guid)).text));
            var db = new ContentDb(ContentDb.Merge(parts.ToArray()));

            var md = new StringBuilder();
            md.AppendLine("# Agnes's nudges");
            md.AppendLine();
            md.AppendLine("Generated by `Tools/unity.sh run LostAndFound.EditorTools.NudgeDump.Write` from the content and `Nudges.cs`.");
            md.AppendLine("Press `H` (gamepad: d-pad ←) during a claim. Each press gives the next nudge for the stage you're at, and");
            md.AppendLine("the list starts again when you move on to the next stage. This is the best path through the week, following each nudge");
            md.AppendLine("as soon as it's given, with the keyboard wording (the gamepad wording names pad buttons instead).");
            md.AppendLine();

            var state = new StoryState();
            var found = new HashSet<string>();
            int count = 0;
            foreach (var day in db.root.days)
            {
                md.AppendLine($"## {day.date}");
                md.AppendLine();
                foreach (var c in Rules.ActiveCases(day, state).ToList())
                {
                    var item = db.Object(c.wants);
                    string who = string.Join(" and ", c.claimants.Select(x => db.Commuter(x)?.name ?? x));
                    if (item != null && !state.InStorage(item, day.day))
                    {
                        state.SetRecord(new CaseRecord { caseId = c.id, verdict = "missing", grade = "skip" });
                        continue;
                    }
                    md.AppendLine($"### {c.id} · {who}{(item != null ? " · " + item.name : " · (nothing in storage)")}");
                    md.AppendLine();
                    var p = new NudgeProgress();
                    if (item != null) foreach (var d in item.details) if (found.Contains(item.id + "." + d.id)) p.found.Add(d.id);
                    for (int guard = 0; guard < 30; guard++)
                    {
                        var list = Nudges.For(db, day.day, c, state, p);
                        var stage = list[0].stage;
                        string about = list[0].detailId != null ? $" ({list[0].detailId})" : "";
                        md.AppendLine($"**{stage}{about}**");
                        md.AppendLine();
                        for (int i = 0; i < list.Count; i++)
                        {
                            string show = list[i].point != NudgePoint.None ? " *[shows " + (list[i].point == NudgePoint.Storage ? "where it is" : "the spot") + "]*" : "";
                            md.AppendLine($"{i + 1}. {list[i].text}{show}");
                            count++;
                        }
                        md.AppendLine();
                        if (item == null || stage == NudgeStage.Decide) break;
                        if (stage == NudgeStage.Find) p.itemSeen = true;
                        else if (stage == NudgeStage.Examine) { p.found.Add(list[0].detailId); found.Add(item.id + "." + list[0].detailId); }
                        else if (stage == NudgeStage.Ask) p.asked.Add(list[0].detailId);
                    }
                    var dec = Rules.Solve(db, day.day, c, state);
                    var vd = Rules.FindVerdict(c, dec.verdict, dec.to);
                    Rules.ApplyVerdict(db, c, vd, dec.to, state);
                    state.SetRecord(new CaseRecord { caseId = c.id, verdict = vd.verdict, to = dec.to, grade = vd.grade });
                }
            }
            File.WriteAllText(Path.Combine(Directory.GetCurrentDirectory(), "docs", "nudges.md"), md.ToString());
            Debug.Log($"[Nudges] wrote docs/nudges.md: {count} nudges");
        }
    }
}
