using System.Collections.Generic;
using UnityEngine;

namespace LostAndFound
{
    /// <summary>
    /// Turns Blender material slot names ("wood_6B4329") into shared URP Lit materials. Each surface
    /// type has a tiling albedo-detail + normal texture pair generated by Tools/textures and stored in
    /// Resources/Textures; the hex is a tint. Materials are cloned from templates in
    /// Resources/Materials so their shader variants survive build stripping.
    /// </summary>
    public static class MaterialLibrary
    {
        struct Surface
        {
            public float metallic, smoothness, normal, tiling, emission;
            public string tex;
            public bool transparent;
            public float alpha;
        }

        static readonly Dictionary<string, Surface> Surfaces = new()
        {
            ["wood"] = new Surface { metallic = 0f, smoothness = 0.46f, normal = 0.6f, tiling = 1f, tex = "wood" },
            ["darkwood"] = new Surface { metallic = 0f, smoothness = 0.5f, normal = 0.5f, tiling = 1f, tex = "wood" },
            ["leather"] = new Surface { metallic = 0f, smoothness = 0.4f, normal = 0.28f, tiling = 9f, tex = "leather" },   // fine grain, not blisters
            ["brass"] = new Surface { metallic = 1f, smoothness = 0.72f, normal = 0.25f, tiling = 1.5f, tex = "brushed" },
            ["gold"] = new Surface { metallic = 1f, smoothness = 0.82f, normal = 0.1f, tiling = 1.5f, tex = "brushed" },
            ["silver"] = new Surface { metallic = 1f, smoothness = 0.8f, normal = 0.15f, tiling = 1.5f, tex = "brushed" },
            ["steel"] = new Surface { metallic = 1f, smoothness = 0.68f, normal = 0.2f, tiling = 1.5f, tex = "brushed" },
            ["iron"] = new Surface { metallic = 0.75f, smoothness = 0.36f, normal = 0.8f, tiling = 1.5f, tex = "iron" },
            ["paper"] = new Surface { metallic = 0f, smoothness = 0.12f, normal = 0.35f, tiling = 2f, tex = "paper" },
            ["card"] = new Surface { metallic = 0f, smoothness = 0.18f, normal = 0.3f, tiling = 2f, tex = "paper" },
            ["cloth"] = new Surface { metallic = 0f, smoothness = 0.08f, normal = 0.6f, tiling = 4f, tex = "cloth" },
            ["felt"] = new Surface { metallic = 0f, smoothness = 0.05f, normal = 0.22f, tiling = 6f, tex = "felt" },
            ["knit"] = new Surface { metallic = 0f, smoothness = 0.05f, normal = 1.0f, tiling = 6f, tex = "knit" },
            ["velvet"] = new Surface { metallic = 0f, smoothness = 0.2f, normal = 0.4f, tiling = 3f, tex = "felt" },
            ["fur"] = new Surface { metallic = 0f, smoothness = 0.05f, normal = 0.8f, tiling = 4f, tex = "felt" },
            ["paint"] = new Surface { metallic = 0f, smoothness = 0.36f, normal = 0.25f, tiling = 1f, tex = "plaster" },
            ["plastic"] = new Surface { metallic = 0f, smoothness = 0.62f, normal = 0.1f, tiling = 1f, tex = "plaster" },
            ["ceramic"] = new Surface { metallic = 0f, smoothness = 0.78f, normal = 0.15f, tiling = 1f, tex = "plaster" },
            ["rubber"] = new Surface { metallic = 0f, smoothness = 0.25f, normal = 0.3f, tiling = 2f, tex = "plaster" },
            ["skin"] = new Surface { metallic = 0f, smoothness = 0.38f, normal = 0.35f, tiling = 3f, tex = "skin" },
            ["hair"] = new Surface { metallic = 0f, smoothness = 0.45f, normal = 0.8f, tiling = 5f, tex = "hair" },
            ["eye"] = new Surface { metallic = 0f, smoothness = 0.92f, normal = 0f, tiling = 1f, tex = null },
            ["emit"] = new Surface { metallic = 0f, smoothness = 0.5f, normal = 0f, tiling = 1f, tex = null, emission = 2.2f },
            ["glass"] = new Surface { metallic = 0f, smoothness = 0.96f, normal = 0.05f, tiling = 1f, tex = "plaster", transparent = true, alpha = 0.10f },
            ["frost"] = new Surface { metallic = 0f, smoothness = 0.7f, normal = 0.6f, tiling = 2f, tex = "frost", transparent = true, alpha = 0.6f },
        };

        static readonly Dictionary<string, Material> Cache = new();
        static readonly Dictionary<string, Texture2D> Textures = new();
        static Material litTemplate, transparentTemplate;
        static readonly int BaseColor = Shader.PropertyToID("_BaseColor");
        static readonly int BaseMap = Shader.PropertyToID("_BaseMap");
        static readonly int BumpMap = Shader.PropertyToID("_BumpMap");
        static readonly int BumpScale = Shader.PropertyToID("_BumpScale");
        static readonly int Metallic = Shader.PropertyToID("_Metallic");
        static readonly int Smoothness = Shader.PropertyToID("_Smoothness");
        static readonly int EmissionColor = Shader.PropertyToID("_EmissionColor");

        public static Material LitTemplate
        {
            get
            {
                if (litTemplate == null) litTemplate = Resources.Load<Material>("Materials/M_Lit");
                if (litTemplate == null) litTemplate = new Material(Shader.Find("Universal Render Pipeline/Lit"));
                return litTemplate;
            }
        }

        public static Material TransparentTemplate
        {
            get
            {
                if (transparentTemplate == null) transparentTemplate = Resources.Load<Material>("Materials/M_LitTransparent");
                if (transparentTemplate == null) transparentTemplate = LitTemplate;
                return transparentTemplate;
            }
        }

        static Texture2D Tex(string name)
        {
            if (string.IsNullOrEmpty(name)) return null;
            if (Textures.TryGetValue(name, out var t)) return t;
            t = Resources.Load<Texture2D>("Textures/" + name);
            Textures[name] = t;
            return t;
        }

        public static bool TryParse(string matName, out string surface, out Color color)
        {
            surface = null;
            color = Color.white;
            if (string.IsNullOrEmpty(matName)) return false;
            string n = matName.Replace(" (Instance)", "");
            int dot = n.IndexOf('.');
            if (dot > 0) n = n.Substring(0, dot); // Blender duplicates: wood_6B4329.001
            int us = n.LastIndexOf('_');
            if (us <= 0) return false;
            surface = n.Substring(0, us).ToLowerInvariant();
            string hex = n.Substring(us + 1);
            if (!Surfaces.ContainsKey(surface)) return false;
            return ColorUtility.TryParseHtmlString("#" + hex, out color);
        }

        /// <summary>Shared material for a Blender slot name, or null if the name isn't ours.</summary>
        public static Material Get(string matName)
        {
            if (matName != null && matName.StartsWith("tex_")) return GetTextured(matName);
            if (!TryParse(matName, out string surface, out Color color)) return null;
            string key = surface + "_" + ColorUtility.ToHtmlStringRGB(color);
            if (Cache.TryGetValue(key, out var m) && m != null) return m;
            m = Create(surface, color);
            m.name = key;
            Cache[key] = m;
            return m;
        }

        /// <summary>"tex_dog_photo" -> a matte material showing Resources/Textures/Items/dog_photo.</summary>
        static Material GetTextured(string matName)
        {
            string n = matName.Replace(" (Instance)", "");
            int dot = n.IndexOf('.');
            if (dot > 0) n = n.Substring(0, dot);
            if (Cache.TryGetValue(n, out var m) && m != null) return m;
            var tex = Resources.Load<Texture2D>("Textures/Items/" + n.Substring(4));
            m = Make(Color.white, tex, 0.22f);
            m.name = n;
            Cache[n] = m;
            return m;
        }

        public static Texture2D ItemTexture(string name) => Resources.Load<Texture2D>("Textures/Items/" + name);

        public static Material Create(string surface, Color color)
        {
            var s = Surfaces[surface];
            var m = new Material(s.transparent ? TransparentTemplate : LitTemplate);
            var albedo = Tex(s.tex == null ? null : s.tex + "_a");
            var normal = Tex(s.tex == null ? null : s.tex + "_n");
            m.SetTexture(BaseMap, albedo != null ? albedo : Texture2D.whiteTexture);
            m.mainTextureScale = Vector2.one * s.tiling;
            if (normal != null && s.normal > 0f)
            {
                m.SetTexture(BumpMap, normal);
                m.SetFloat(BumpScale, s.normal);
                m.EnableKeyword("_NORMALMAP");
            }
            else
            {
                // keep the template's keywords (the build only ships those shader variants);
                // a null bump map falls back to the shader's flat default
                m.SetTexture(BumpMap, null);
                m.EnableKeyword("_NORMALMAP");
            }
            if (s.transparent) color.a = s.alpha;
            m.SetColor(BaseColor, color);
            m.SetFloat(Metallic, s.metallic);
            m.SetFloat(Smoothness, s.smoothness);
            m.SetColor(EmissionColor, s.emission > 0 ? color * s.emission : Color.black);
            m.EnableKeyword("_EMISSION");
            m.globalIlluminationFlags = MaterialGlobalIlluminationFlags.None;
            return m;
        }

        /// <summary>Replace every renderer's Blender materials under `root` with library materials.</summary>
        public static void Apply(GameObject root)
        {
            foreach (var r in root.GetComponentsInChildren<Renderer>(true))
            {
                var mats = r.sharedMaterials;
                bool changed = false;
                for (int i = 0; i < mats.Length; i++)
                {
                    if (mats[i] == null) continue;
                    var lib = Get(mats[i].name);
                    if (lib != null) { mats[i] = lib; changed = true; }
                }
                if (changed) r.sharedMaterials = mats;
            }
        }

        /// <summary>A plain material for runtime-built geometry (paper tags, slips, photographs).</summary>
        public static Material Make(Color color, Texture tex = null, float smoothness = 0.15f, bool transparent = false)
        {
            var m = new Material(transparent ? TransparentTemplate : LitTemplate);
            m.SetTexture(BaseMap, tex != null ? tex : Texture2D.whiteTexture);
            m.mainTextureScale = Vector2.one;
            m.SetColor(BaseColor, color);
            m.SetFloat(Metallic, 0f);
            m.SetFloat(Smoothness, smoothness);
            m.SetTexture(BumpMap, null);
            m.EnableKeyword("_NORMALMAP");   // see Create: stay on a shipped variant
            m.SetColor(EmissionColor, Color.black);
            m.EnableKeyword("_EMISSION");
            return m;
        }

        public static void SetEmission(Material m, Color c) => m.SetColor(EmissionColor, c);

        /// <summary>Glowing violet "hidden ink" for UV overlays (transparent, emissive).</summary>
        public static void MakeUvInk(Material m)
        {
            var tex = m.GetTexture(BaseMap);
            m.shader = TransparentTemplate.shader;
            m.CopyPropertiesFromMaterial(TransparentTemplate);
            m.SetTexture(BaseMap, tex);
            m.SetColor(BaseColor, new Color(0.75f, 0.6f, 1f, 1f));
            m.SetTexture("_EmissionMap", tex);
            m.SetColor(EmissionColor, new Color(0.7f, 0.5f, 1.6f));
            m.EnableKeyword("_EMISSION");
        }
    }
}
